spring.datasource.url=jdbc:postgresql://postgres:5432/task350
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.kafka.bootstrap-servers=kafka:29092

spring.data.redis.host=redis
spring.data.redis.port=6379
