server.port=24130

spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=distcomp
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
spring.cassandra.schema-action=recreate_drop_unused

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:cassandra://localhost:9042/distcomp
spring.liquibase.user=${LIQUIDBASE_USER}
spring.liquibase.password=${LIQUIDBASE_PASSWORD}

spring.liquibase.enabled=false
spring.liquibase.driver-class-name=com.simba.cassandra.jdbc42.Driver

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=discussion-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer