/**
 *
 *  Databasechangelog.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace distcomp
{

class Databasechangelog
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _author;
        static const std::string _filename;
        static const std::string _dateexecuted;
        static const std::string _orderexecuted;
        static const std::string _exectype;
        static const std::string _md5sum;
        static const std::string _description;
        static const std::string _comments;
        static const std::string _tag;
        static const std::string _liquibase;
        static const std::string _contexts;
        static const std::string _labels;
        static const std::string _deployment_id;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = void;
    int getPrimaryKey() const { assert(false); return 0; }

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Databasechangelog(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Databasechangelog(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Databasechangelog(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Databasechangelog() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column author  */
    ///Get the value of the column author, returns the default value if the column is null
    const std::string &getValueOfAuthor() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAuthor() const noexcept;
    ///Set the value of the column author
    void setAuthor(const std::string &pAuthor) noexcept;
    void setAuthor(std::string &&pAuthor) noexcept;

    /**  For column filename  */
    ///Get the value of the column filename, returns the default value if the column is null
    const std::string &getValueOfFilename() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFilename() const noexcept;
    ///Set the value of the column filename
    void setFilename(const std::string &pFilename) noexcept;
    void setFilename(std::string &&pFilename) noexcept;

    /**  For column dateexecuted  */
    ///Get the value of the column dateexecuted, returns the default value if the column is null
    const ::trantor::Date &getValueOfDateexecuted() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getDateexecuted() const noexcept;
    ///Set the value of the column dateexecuted
    void setDateexecuted(const ::trantor::Date &pDateexecuted) noexcept;

    /**  For column orderexecuted  */
    ///Get the value of the column orderexecuted, returns the default value if the column is null
    const int32_t &getValueOfOrderexecuted() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getOrderexecuted() const noexcept;
    ///Set the value of the column orderexecuted
    void setOrderexecuted(const int32_t &pOrderexecuted) noexcept;

    /**  For column exectype  */
    ///Get the value of the column exectype, returns the default value if the column is null
    const std::string &getValueOfExectype() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getExectype() const noexcept;
    ///Set the value of the column exectype
    void setExectype(const std::string &pExectype) noexcept;
    void setExectype(std::string &&pExectype) noexcept;

    /**  For column md5sum  */
    ///Get the value of the column md5sum, returns the default value if the column is null
    const std::string &getValueOfMd5sum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMd5sum() const noexcept;
    ///Set the value of the column md5sum
    void setMd5sum(const std::string &pMd5sum) noexcept;
    void setMd5sum(std::string &&pMd5sum) noexcept;
    void setMd5sumToNull() noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column comments  */
    ///Get the value of the column comments, returns the default value if the column is null
    const std::string &getValueOfComments() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getComments() const noexcept;
    ///Set the value of the column comments
    void setComments(const std::string &pComments) noexcept;
    void setComments(std::string &&pComments) noexcept;
    void setCommentsToNull() noexcept;

    /**  For column tag  */
    ///Get the value of the column tag, returns the default value if the column is null
    const std::string &getValueOfTag() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTag() const noexcept;
    ///Set the value of the column tag
    void setTag(const std::string &pTag) noexcept;
    void setTag(std::string &&pTag) noexcept;
    void setTagToNull() noexcept;

    /**  For column liquibase  */
    ///Get the value of the column liquibase, returns the default value if the column is null
    const std::string &getValueOfLiquibase() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLiquibase() const noexcept;
    ///Set the value of the column liquibase
    void setLiquibase(const std::string &pLiquibase) noexcept;
    void setLiquibase(std::string &&pLiquibase) noexcept;
    void setLiquibaseToNull() noexcept;

    /**  For column contexts  */
    ///Get the value of the column contexts, returns the default value if the column is null
    const std::string &getValueOfContexts() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getContexts() const noexcept;
    ///Set the value of the column contexts
    void setContexts(const std::string &pContexts) noexcept;
    void setContexts(std::string &&pContexts) noexcept;
    void setContextsToNull() noexcept;

    /**  For column labels  */
    ///Get the value of the column labels, returns the default value if the column is null
    const std::string &getValueOfLabels() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLabels() const noexcept;
    ///Set the value of the column labels
    void setLabels(const std::string &pLabels) noexcept;
    void setLabels(std::string &&pLabels) noexcept;
    void setLabelsToNull() noexcept;

    /**  For column deployment_id  */
    ///Get the value of the column deployment_id, returns the default value if the column is null
    const std::string &getValueOfDeploymentId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDeploymentId() const noexcept;
    ///Set the value of the column deployment_id
    void setDeploymentId(const std::string &pDeploymentId) noexcept;
    void setDeploymentId(std::string &&pDeploymentId) noexcept;
    void setDeploymentIdToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 14;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Databasechangelog>;
    friend drogon::orm::BaseBuilder<Databasechangelog, true, true>;
    friend drogon::orm::BaseBuilder<Databasechangelog, true, false>;
    friend drogon::orm::BaseBuilder<Databasechangelog, false, true>;
    friend drogon::orm::BaseBuilder<Databasechangelog, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Databasechangelog>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> author_;
    std::shared_ptr<std::string> filename_;
    std::shared_ptr<::trantor::Date> dateexecuted_;
    std::shared_ptr<int32_t> orderexecuted_;
    std::shared_ptr<std::string> exectype_;
    std::shared_ptr<std::string> md5sum_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<std::string> comments_;
    std::shared_ptr<std::string> tag_;
    std::shared_ptr<std::string> liquibase_;
    std::shared_ptr<std::string> contexts_;
    std::shared_ptr<std::string> labels_;
    std::shared_ptr<std::string> deploymentId_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[14]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "author,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "filename,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "dateexecuted,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "orderexecuted,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "exectype,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "md5sum,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "description,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "comments,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "tag,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "liquibase,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "contexts,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "labels,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "deployment_id,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace distcomp
} // namespace drogon_model
