/**
 *
 *  Databasechangeloglock.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Databasechangeloglock.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::distcomp;

const std::string Databasechangeloglock::Cols::_id = "\"id\"";
const std::string Databasechangeloglock::Cols::_locked = "\"locked\"";
const std::string Databasechangeloglock::Cols::_lockgranted = "\"lockgranted\"";
const std::string Databasechangeloglock::Cols::_lockedby = "\"lockedby\"";
const std::string Databasechangeloglock::primaryKeyName = "id";
const bool Databasechangeloglock::hasPrimaryKey = true;
const std::string Databasechangeloglock::tableName = "\"databasechangeloglock\"";

const std::vector<typename Databasechangeloglock::MetaData> Databasechangeloglock::metaData_={
{"id","int32_t","integer",4,0,1,1},
{"locked","bool","boolean",1,0,0,1},
{"lockgranted","::trantor::Date","timestamp without time zone",0,0,0,0},
{"lockedby","std::string","character varying",255,0,0,0}
};
const std::string &Databasechangeloglock::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Databasechangeloglock::Databasechangeloglock(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["locked"].isNull())
        {
            locked_=std::make_shared<bool>(r["locked"].as<bool>());
        }
        if(!r["lockgranted"].isNull())
        {
            auto timeStr = r["lockgranted"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lockgranted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["lockedby"].isNull())
        {
            lockedby_=std::make_shared<std::string>(r["lockedby"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            locked_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lockgranted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            lockedby_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Databasechangeloglock::Databasechangeloglock(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            locked_=std::make_shared<bool>(pJson[pMasqueradingVector[1]].asBool());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lockgranted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            lockedby_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

Databasechangeloglock::Databasechangeloglock(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("locked"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["locked"].isNull())
        {
            locked_=std::make_shared<bool>(pJson["locked"].asBool());
        }
    }
    if(pJson.isMember("lockgranted"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["lockgranted"].isNull())
        {
            auto timeStr = pJson["lockgranted"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lockgranted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("lockedby"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["lockedby"].isNull())
        {
            lockedby_=std::make_shared<std::string>(pJson["lockedby"].asString());
        }
    }
}

void Databasechangeloglock::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            locked_=std::make_shared<bool>(pJson[pMasqueradingVector[1]].asBool());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lockgranted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            lockedby_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void Databasechangeloglock::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("locked"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["locked"].isNull())
        {
            locked_=std::make_shared<bool>(pJson["locked"].asBool());
        }
    }
    if(pJson.isMember("lockgranted"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["lockgranted"].isNull())
        {
            auto timeStr = pJson["lockgranted"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lockgranted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("lockedby"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["lockedby"].isNull())
        {
            lockedby_=std::make_shared<std::string>(pJson["lockedby"].asString());
        }
    }
}

const int32_t &Databasechangeloglock::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Databasechangeloglock::getId() const noexcept
{
    return id_;
}
void Databasechangeloglock::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Databasechangeloglock::PrimaryKeyType & Databasechangeloglock::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const bool &Databasechangeloglock::getValueOfLocked() const noexcept
{
    static const bool defaultValue = bool();
    if(locked_)
        return *locked_;
    return defaultValue;
}
const std::shared_ptr<bool> &Databasechangeloglock::getLocked() const noexcept
{
    return locked_;
}
void Databasechangeloglock::setLocked(const bool &pLocked) noexcept
{
    locked_ = std::make_shared<bool>(pLocked);
    dirtyFlag_[1] = true;
}

const ::trantor::Date &Databasechangeloglock::getValueOfLockgranted() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lockgranted_)
        return *lockgranted_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Databasechangeloglock::getLockgranted() const noexcept
{
    return lockgranted_;
}
void Databasechangeloglock::setLockgranted(const ::trantor::Date &pLockgranted) noexcept
{
    lockgranted_ = std::make_shared<::trantor::Date>(pLockgranted);
    dirtyFlag_[2] = true;
}
void Databasechangeloglock::setLockgrantedToNull() noexcept
{
    lockgranted_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Databasechangeloglock::getValueOfLockedby() const noexcept
{
    static const std::string defaultValue = std::string();
    if(lockedby_)
        return *lockedby_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangeloglock::getLockedby() const noexcept
{
    return lockedby_;
}
void Databasechangeloglock::setLockedby(const std::string &pLockedby) noexcept
{
    lockedby_ = std::make_shared<std::string>(pLockedby);
    dirtyFlag_[3] = true;
}
void Databasechangeloglock::setLockedby(std::string &&pLockedby) noexcept
{
    lockedby_ = std::make_shared<std::string>(std::move(pLockedby));
    dirtyFlag_[3] = true;
}
void Databasechangeloglock::setLockedbyToNull() noexcept
{
    lockedby_.reset();
    dirtyFlag_[3] = true;
}

void Databasechangeloglock::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Databasechangeloglock::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "locked",
        "lockgranted",
        "lockedby"
    };
    return inCols;
}

void Databasechangeloglock::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getLocked())
        {
            binder << getValueOfLocked();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLockgranted())
        {
            binder << getValueOfLockgranted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLockedby())
        {
            binder << getValueOfLockedby();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Databasechangeloglock::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Databasechangeloglock::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getLocked())
        {
            binder << getValueOfLocked();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLockgranted())
        {
            binder << getValueOfLockgranted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLockedby())
        {
            binder << getValueOfLockedby();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Databasechangeloglock::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getLocked())
    {
        ret["locked"]=getValueOfLocked();
    }
    else
    {
        ret["locked"]=Json::Value();
    }
    if(getLockgranted())
    {
        ret["lockgranted"]=getLockgranted()->toDbStringLocal();
    }
    else
    {
        ret["lockgranted"]=Json::Value();
    }
    if(getLockedby())
    {
        ret["lockedby"]=getValueOfLockedby();
    }
    else
    {
        ret["lockedby"]=Json::Value();
    }
    return ret;
}

std::string Databasechangeloglock::toString() const
{
    return toJson().toStyledString();
}

Json::Value Databasechangeloglock::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getLocked())
            {
                ret[pMasqueradingVector[1]]=getValueOfLocked();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getLockgranted())
            {
                ret[pMasqueradingVector[2]]=getLockgranted()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getLockedby())
            {
                ret[pMasqueradingVector[3]]=getValueOfLockedby();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getLocked())
    {
        ret["locked"]=getValueOfLocked();
    }
    else
    {
        ret["locked"]=Json::Value();
    }
    if(getLockgranted())
    {
        ret["lockgranted"]=getLockgranted()->toDbStringLocal();
    }
    else
    {
        ret["lockgranted"]=Json::Value();
    }
    if(getLockedby())
    {
        ret["lockedby"]=getValueOfLockedby();
    }
    else
    {
        ret["lockedby"]=Json::Value();
    }
    return ret;
}

bool Databasechangeloglock::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("locked"))
    {
        if(!validJsonOfField(1, "locked", pJson["locked"], err, true))
            return false;
    }
    else
    {
        err="The locked column cannot be null";
        return false;
    }
    if(pJson.isMember("lockgranted"))
    {
        if(!validJsonOfField(2, "lockgranted", pJson["lockgranted"], err, true))
            return false;
    }
    if(pJson.isMember("lockedby"))
    {
        if(!validJsonOfField(3, "lockedby", pJson["lockedby"], err, true))
            return false;
    }
    return true;
}
bool Databasechangeloglock::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                               const std::vector<std::string> &pMasqueradingVector,
                                                               std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Databasechangeloglock::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("locked"))
    {
        if(!validJsonOfField(1, "locked", pJson["locked"], err, false))
            return false;
    }
    if(pJson.isMember("lockgranted"))
    {
        if(!validJsonOfField(2, "lockgranted", pJson["lockgranted"], err, false))
            return false;
    }
    if(pJson.isMember("lockedby"))
    {
        if(!validJsonOfField(3, "lockedby", pJson["lockedby"], err, false))
            return false;
    }
    return true;
}
bool Databasechangeloglock::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Databasechangeloglock::validJsonOfField(size_t index,
                                             const std::string &fieldName,
                                             const Json::Value &pJson,
                                             std::string &err,
                                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
