/**
 *
 *  Databasechangelog.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Databasechangelog.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::distcomp;

const std::string Databasechangelog::Cols::_id = "\"id\"";
const std::string Databasechangelog::Cols::_author = "\"author\"";
const std::string Databasechangelog::Cols::_filename = "\"filename\"";
const std::string Databasechangelog::Cols::_dateexecuted = "\"dateexecuted\"";
const std::string Databasechangelog::Cols::_orderexecuted = "\"orderexecuted\"";
const std::string Databasechangelog::Cols::_exectype = "\"exectype\"";
const std::string Databasechangelog::Cols::_md5sum = "\"md5sum\"";
const std::string Databasechangelog::Cols::_description = "\"description\"";
const std::string Databasechangelog::Cols::_comments = "\"comments\"";
const std::string Databasechangelog::Cols::_tag = "\"tag\"";
const std::string Databasechangelog::Cols::_liquibase = "\"liquibase\"";
const std::string Databasechangelog::Cols::_contexts = "\"contexts\"";
const std::string Databasechangelog::Cols::_labels = "\"labels\"";
const std::string Databasechangelog::Cols::_deployment_id = "\"deployment_id\"";
const std::string Databasechangelog::primaryKeyName = "";
const bool Databasechangelog::hasPrimaryKey = false;
const std::string Databasechangelog::tableName = "\"databasechangelog\"";

const std::vector<typename Databasechangelog::MetaData> Databasechangelog::metaData_={
{"id","std::string","character varying",255,0,0,1},
{"author","std::string","character varying",255,0,0,1},
{"filename","std::string","character varying",255,0,0,1},
{"dateexecuted","::trantor::Date","timestamp without time zone",0,0,0,1},
{"orderexecuted","int32_t","integer",4,0,0,1},
{"exectype","std::string","character varying",10,0,0,1},
{"md5sum","std::string","character varying",35,0,0,0},
{"description","std::string","character varying",255,0,0,0},
{"comments","std::string","character varying",255,0,0,0},
{"tag","std::string","character varying",255,0,0,0},
{"liquibase","std::string","character varying",20,0,0,0},
{"contexts","std::string","character varying",255,0,0,0},
{"labels","std::string","character varying",255,0,0,0},
{"deployment_id","std::string","character varying",10,0,0,0}
};
const std::string &Databasechangelog::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Databasechangelog::Databasechangelog(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["author"].isNull())
        {
            author_=std::make_shared<std::string>(r["author"].as<std::string>());
        }
        if(!r["filename"].isNull())
        {
            filename_=std::make_shared<std::string>(r["filename"].as<std::string>());
        }
        if(!r["dateexecuted"].isNull())
        {
            auto timeStr = r["dateexecuted"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateexecuted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["orderexecuted"].isNull())
        {
            orderexecuted_=std::make_shared<int32_t>(r["orderexecuted"].as<int32_t>());
        }
        if(!r["exectype"].isNull())
        {
            exectype_=std::make_shared<std::string>(r["exectype"].as<std::string>());
        }
        if(!r["md5sum"].isNull())
        {
            md5sum_=std::make_shared<std::string>(r["md5sum"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["comments"].isNull())
        {
            comments_=std::make_shared<std::string>(r["comments"].as<std::string>());
        }
        if(!r["tag"].isNull())
        {
            tag_=std::make_shared<std::string>(r["tag"].as<std::string>());
        }
        if(!r["liquibase"].isNull())
        {
            liquibase_=std::make_shared<std::string>(r["liquibase"].as<std::string>());
        }
        if(!r["contexts"].isNull())
        {
            contexts_=std::make_shared<std::string>(r["contexts"].as<std::string>());
        }
        if(!r["labels"].isNull())
        {
            labels_=std::make_shared<std::string>(r["labels"].as<std::string>());
        }
        if(!r["deployment_id"].isNull())
        {
            deploymentId_=std::make_shared<std::string>(r["deployment_id"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 14 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            author_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            filename_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateexecuted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            orderexecuted_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            exectype_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            md5sum_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            comments_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            tag_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            liquibase_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            contexts_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            labels_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            deploymentId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Databasechangelog::Databasechangelog(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            author_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            filename_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateexecuted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            orderexecuted_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            exectype_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            md5sum_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            comments_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            tag_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            liquibase_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            contexts_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            labels_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            deploymentId_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
}

Databasechangelog::Databasechangelog(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("author"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["author"].isNull())
        {
            author_=std::make_shared<std::string>(pJson["author"].asString());
        }
    }
    if(pJson.isMember("filename"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["filename"].isNull())
        {
            filename_=std::make_shared<std::string>(pJson["filename"].asString());
        }
    }
    if(pJson.isMember("dateexecuted"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["dateexecuted"].isNull())
        {
            auto timeStr = pJson["dateexecuted"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateexecuted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("orderexecuted"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["orderexecuted"].isNull())
        {
            orderexecuted_=std::make_shared<int32_t>((int32_t)pJson["orderexecuted"].asInt64());
        }
    }
    if(pJson.isMember("exectype"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["exectype"].isNull())
        {
            exectype_=std::make_shared<std::string>(pJson["exectype"].asString());
        }
    }
    if(pJson.isMember("md5sum"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["md5sum"].isNull())
        {
            md5sum_=std::make_shared<std::string>(pJson["md5sum"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("comments"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["comments"].isNull())
        {
            comments_=std::make_shared<std::string>(pJson["comments"].asString());
        }
    }
    if(pJson.isMember("tag"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["tag"].isNull())
        {
            tag_=std::make_shared<std::string>(pJson["tag"].asString());
        }
    }
    if(pJson.isMember("liquibase"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["liquibase"].isNull())
        {
            liquibase_=std::make_shared<std::string>(pJson["liquibase"].asString());
        }
    }
    if(pJson.isMember("contexts"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["contexts"].isNull())
        {
            contexts_=std::make_shared<std::string>(pJson["contexts"].asString());
        }
    }
    if(pJson.isMember("labels"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["labels"].isNull())
        {
            labels_=std::make_shared<std::string>(pJson["labels"].asString());
        }
    }
    if(pJson.isMember("deployment_id"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["deployment_id"].isNull())
        {
            deploymentId_=std::make_shared<std::string>(pJson["deployment_id"].asString());
        }
    }
}

void Databasechangelog::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            author_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            filename_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateexecuted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            orderexecuted_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            exectype_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            md5sum_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            comments_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            tag_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            liquibase_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            contexts_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            labels_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            deploymentId_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
}

void Databasechangelog::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0] = true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("author"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["author"].isNull())
        {
            author_=std::make_shared<std::string>(pJson["author"].asString());
        }
    }
    if(pJson.isMember("filename"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["filename"].isNull())
        {
            filename_=std::make_shared<std::string>(pJson["filename"].asString());
        }
    }
    if(pJson.isMember("dateexecuted"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["dateexecuted"].isNull())
        {
            auto timeStr = pJson["dateexecuted"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateexecuted_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("orderexecuted"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["orderexecuted"].isNull())
        {
            orderexecuted_=std::make_shared<int32_t>((int32_t)pJson["orderexecuted"].asInt64());
        }
    }
    if(pJson.isMember("exectype"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["exectype"].isNull())
        {
            exectype_=std::make_shared<std::string>(pJson["exectype"].asString());
        }
    }
    if(pJson.isMember("md5sum"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["md5sum"].isNull())
        {
            md5sum_=std::make_shared<std::string>(pJson["md5sum"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("comments"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["comments"].isNull())
        {
            comments_=std::make_shared<std::string>(pJson["comments"].asString());
        }
    }
    if(pJson.isMember("tag"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["tag"].isNull())
        {
            tag_=std::make_shared<std::string>(pJson["tag"].asString());
        }
    }
    if(pJson.isMember("liquibase"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["liquibase"].isNull())
        {
            liquibase_=std::make_shared<std::string>(pJson["liquibase"].asString());
        }
    }
    if(pJson.isMember("contexts"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["contexts"].isNull())
        {
            contexts_=std::make_shared<std::string>(pJson["contexts"].asString());
        }
    }
    if(pJson.isMember("labels"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["labels"].isNull())
        {
            labels_=std::make_shared<std::string>(pJson["labels"].asString());
        }
    }
    if(pJson.isMember("deployment_id"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["deployment_id"].isNull())
        {
            deploymentId_=std::make_shared<std::string>(pJson["deployment_id"].asString());
        }
    }
}

const std::string &Databasechangelog::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getId() const noexcept
{
    return id_;
}
void Databasechangelog::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void Databasechangelog::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}

const std::string &Databasechangelog::getValueOfAuthor() const noexcept
{
    static const std::string defaultValue = std::string();
    if(author_)
        return *author_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getAuthor() const noexcept
{
    return author_;
}
void Databasechangelog::setAuthor(const std::string &pAuthor) noexcept
{
    author_ = std::make_shared<std::string>(pAuthor);
    dirtyFlag_[1] = true;
}
void Databasechangelog::setAuthor(std::string &&pAuthor) noexcept
{
    author_ = std::make_shared<std::string>(std::move(pAuthor));
    dirtyFlag_[1] = true;
}

const std::string &Databasechangelog::getValueOfFilename() const noexcept
{
    static const std::string defaultValue = std::string();
    if(filename_)
        return *filename_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getFilename() const noexcept
{
    return filename_;
}
void Databasechangelog::setFilename(const std::string &pFilename) noexcept
{
    filename_ = std::make_shared<std::string>(pFilename);
    dirtyFlag_[2] = true;
}
void Databasechangelog::setFilename(std::string &&pFilename) noexcept
{
    filename_ = std::make_shared<std::string>(std::move(pFilename));
    dirtyFlag_[2] = true;
}

const ::trantor::Date &Databasechangelog::getValueOfDateexecuted() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(dateexecuted_)
        return *dateexecuted_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Databasechangelog::getDateexecuted() const noexcept
{
    return dateexecuted_;
}
void Databasechangelog::setDateexecuted(const ::trantor::Date &pDateexecuted) noexcept
{
    dateexecuted_ = std::make_shared<::trantor::Date>(pDateexecuted);
    dirtyFlag_[3] = true;
}

const int32_t &Databasechangelog::getValueOfOrderexecuted() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(orderexecuted_)
        return *orderexecuted_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Databasechangelog::getOrderexecuted() const noexcept
{
    return orderexecuted_;
}
void Databasechangelog::setOrderexecuted(const int32_t &pOrderexecuted) noexcept
{
    orderexecuted_ = std::make_shared<int32_t>(pOrderexecuted);
    dirtyFlag_[4] = true;
}

const std::string &Databasechangelog::getValueOfExectype() const noexcept
{
    static const std::string defaultValue = std::string();
    if(exectype_)
        return *exectype_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getExectype() const noexcept
{
    return exectype_;
}
void Databasechangelog::setExectype(const std::string &pExectype) noexcept
{
    exectype_ = std::make_shared<std::string>(pExectype);
    dirtyFlag_[5] = true;
}
void Databasechangelog::setExectype(std::string &&pExectype) noexcept
{
    exectype_ = std::make_shared<std::string>(std::move(pExectype));
    dirtyFlag_[5] = true;
}

const std::string &Databasechangelog::getValueOfMd5sum() const noexcept
{
    static const std::string defaultValue = std::string();
    if(md5sum_)
        return *md5sum_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getMd5sum() const noexcept
{
    return md5sum_;
}
void Databasechangelog::setMd5sum(const std::string &pMd5sum) noexcept
{
    md5sum_ = std::make_shared<std::string>(pMd5sum);
    dirtyFlag_[6] = true;
}
void Databasechangelog::setMd5sum(std::string &&pMd5sum) noexcept
{
    md5sum_ = std::make_shared<std::string>(std::move(pMd5sum));
    dirtyFlag_[6] = true;
}
void Databasechangelog::setMd5sumToNull() noexcept
{
    md5sum_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Databasechangelog::getValueOfDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getDescription() const noexcept
{
    return description_;
}
void Databasechangelog::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[7] = true;
}
void Databasechangelog::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[7] = true;
}
void Databasechangelog::setDescriptionToNull() noexcept
{
    description_.reset();
    dirtyFlag_[7] = true;
}

const std::string &Databasechangelog::getValueOfComments() const noexcept
{
    static const std::string defaultValue = std::string();
    if(comments_)
        return *comments_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getComments() const noexcept
{
    return comments_;
}
void Databasechangelog::setComments(const std::string &pComments) noexcept
{
    comments_ = std::make_shared<std::string>(pComments);
    dirtyFlag_[8] = true;
}
void Databasechangelog::setComments(std::string &&pComments) noexcept
{
    comments_ = std::make_shared<std::string>(std::move(pComments));
    dirtyFlag_[8] = true;
}
void Databasechangelog::setCommentsToNull() noexcept
{
    comments_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Databasechangelog::getValueOfTag() const noexcept
{
    static const std::string defaultValue = std::string();
    if(tag_)
        return *tag_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getTag() const noexcept
{
    return tag_;
}
void Databasechangelog::setTag(const std::string &pTag) noexcept
{
    tag_ = std::make_shared<std::string>(pTag);
    dirtyFlag_[9] = true;
}
void Databasechangelog::setTag(std::string &&pTag) noexcept
{
    tag_ = std::make_shared<std::string>(std::move(pTag));
    dirtyFlag_[9] = true;
}
void Databasechangelog::setTagToNull() noexcept
{
    tag_.reset();
    dirtyFlag_[9] = true;
}

const std::string &Databasechangelog::getValueOfLiquibase() const noexcept
{
    static const std::string defaultValue = std::string();
    if(liquibase_)
        return *liquibase_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getLiquibase() const noexcept
{
    return liquibase_;
}
void Databasechangelog::setLiquibase(const std::string &pLiquibase) noexcept
{
    liquibase_ = std::make_shared<std::string>(pLiquibase);
    dirtyFlag_[10] = true;
}
void Databasechangelog::setLiquibase(std::string &&pLiquibase) noexcept
{
    liquibase_ = std::make_shared<std::string>(std::move(pLiquibase));
    dirtyFlag_[10] = true;
}
void Databasechangelog::setLiquibaseToNull() noexcept
{
    liquibase_.reset();
    dirtyFlag_[10] = true;
}

const std::string &Databasechangelog::getValueOfContexts() const noexcept
{
    static const std::string defaultValue = std::string();
    if(contexts_)
        return *contexts_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getContexts() const noexcept
{
    return contexts_;
}
void Databasechangelog::setContexts(const std::string &pContexts) noexcept
{
    contexts_ = std::make_shared<std::string>(pContexts);
    dirtyFlag_[11] = true;
}
void Databasechangelog::setContexts(std::string &&pContexts) noexcept
{
    contexts_ = std::make_shared<std::string>(std::move(pContexts));
    dirtyFlag_[11] = true;
}
void Databasechangelog::setContextsToNull() noexcept
{
    contexts_.reset();
    dirtyFlag_[11] = true;
}

const std::string &Databasechangelog::getValueOfLabels() const noexcept
{
    static const std::string defaultValue = std::string();
    if(labels_)
        return *labels_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getLabels() const noexcept
{
    return labels_;
}
void Databasechangelog::setLabels(const std::string &pLabels) noexcept
{
    labels_ = std::make_shared<std::string>(pLabels);
    dirtyFlag_[12] = true;
}
void Databasechangelog::setLabels(std::string &&pLabels) noexcept
{
    labels_ = std::make_shared<std::string>(std::move(pLabels));
    dirtyFlag_[12] = true;
}
void Databasechangelog::setLabelsToNull() noexcept
{
    labels_.reset();
    dirtyFlag_[12] = true;
}

const std::string &Databasechangelog::getValueOfDeploymentId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(deploymentId_)
        return *deploymentId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Databasechangelog::getDeploymentId() const noexcept
{
    return deploymentId_;
}
void Databasechangelog::setDeploymentId(const std::string &pDeploymentId) noexcept
{
    deploymentId_ = std::make_shared<std::string>(pDeploymentId);
    dirtyFlag_[13] = true;
}
void Databasechangelog::setDeploymentId(std::string &&pDeploymentId) noexcept
{
    deploymentId_ = std::make_shared<std::string>(std::move(pDeploymentId));
    dirtyFlag_[13] = true;
}
void Databasechangelog::setDeploymentIdToNull() noexcept
{
    deploymentId_.reset();
    dirtyFlag_[13] = true;
}

void Databasechangelog::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Databasechangelog::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "author",
        "filename",
        "dateexecuted",
        "orderexecuted",
        "exectype",
        "md5sum",
        "description",
        "comments",
        "tag",
        "liquibase",
        "contexts",
        "labels",
        "deployment_id"
    };
    return inCols;
}

void Databasechangelog::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAuthor())
        {
            binder << getValueOfAuthor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getFilename())
        {
            binder << getValueOfFilename();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDateexecuted())
        {
            binder << getValueOfDateexecuted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getOrderexecuted())
        {
            binder << getValueOfOrderexecuted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getExectype())
        {
            binder << getValueOfExectype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMd5sum())
        {
            binder << getValueOfMd5sum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getComments())
        {
            binder << getValueOfComments();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getTag())
        {
            binder << getValueOfTag();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getLiquibase())
        {
            binder << getValueOfLiquibase();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getContexts())
        {
            binder << getValueOfContexts();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getLabels())
        {
            binder << getValueOfLabels();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getDeploymentId())
        {
            binder << getValueOfDeploymentId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Databasechangelog::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    return ret;
}

void Databasechangelog::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAuthor())
        {
            binder << getValueOfAuthor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getFilename())
        {
            binder << getValueOfFilename();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDateexecuted())
        {
            binder << getValueOfDateexecuted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getOrderexecuted())
        {
            binder << getValueOfOrderexecuted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getExectype())
        {
            binder << getValueOfExectype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMd5sum())
        {
            binder << getValueOfMd5sum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getComments())
        {
            binder << getValueOfComments();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getTag())
        {
            binder << getValueOfTag();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getLiquibase())
        {
            binder << getValueOfLiquibase();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getContexts())
        {
            binder << getValueOfContexts();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getLabels())
        {
            binder << getValueOfLabels();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getDeploymentId())
        {
            binder << getValueOfDeploymentId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Databasechangelog::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAuthor())
    {
        ret["author"]=getValueOfAuthor();
    }
    else
    {
        ret["author"]=Json::Value();
    }
    if(getFilename())
    {
        ret["filename"]=getValueOfFilename();
    }
    else
    {
        ret["filename"]=Json::Value();
    }
    if(getDateexecuted())
    {
        ret["dateexecuted"]=getDateexecuted()->toDbStringLocal();
    }
    else
    {
        ret["dateexecuted"]=Json::Value();
    }
    if(getOrderexecuted())
    {
        ret["orderexecuted"]=getValueOfOrderexecuted();
    }
    else
    {
        ret["orderexecuted"]=Json::Value();
    }
    if(getExectype())
    {
        ret["exectype"]=getValueOfExectype();
    }
    else
    {
        ret["exectype"]=Json::Value();
    }
    if(getMd5sum())
    {
        ret["md5sum"]=getValueOfMd5sum();
    }
    else
    {
        ret["md5sum"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getComments())
    {
        ret["comments"]=getValueOfComments();
    }
    else
    {
        ret["comments"]=Json::Value();
    }
    if(getTag())
    {
        ret["tag"]=getValueOfTag();
    }
    else
    {
        ret["tag"]=Json::Value();
    }
    if(getLiquibase())
    {
        ret["liquibase"]=getValueOfLiquibase();
    }
    else
    {
        ret["liquibase"]=Json::Value();
    }
    if(getContexts())
    {
        ret["contexts"]=getValueOfContexts();
    }
    else
    {
        ret["contexts"]=Json::Value();
    }
    if(getLabels())
    {
        ret["labels"]=getValueOfLabels();
    }
    else
    {
        ret["labels"]=Json::Value();
    }
    if(getDeploymentId())
    {
        ret["deployment_id"]=getValueOfDeploymentId();
    }
    else
    {
        ret["deployment_id"]=Json::Value();
    }
    return ret;
}

std::string Databasechangelog::toString() const
{
    return toJson().toStyledString();
}

Json::Value Databasechangelog::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 14)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAuthor())
            {
                ret[pMasqueradingVector[1]]=getValueOfAuthor();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getFilename())
            {
                ret[pMasqueradingVector[2]]=getValueOfFilename();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDateexecuted())
            {
                ret[pMasqueradingVector[3]]=getDateexecuted()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getOrderexecuted())
            {
                ret[pMasqueradingVector[4]]=getValueOfOrderexecuted();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getExectype())
            {
                ret[pMasqueradingVector[5]]=getValueOfExectype();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getMd5sum())
            {
                ret[pMasqueradingVector[6]]=getValueOfMd5sum();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[7]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getComments())
            {
                ret[pMasqueradingVector[8]]=getValueOfComments();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getTag())
            {
                ret[pMasqueradingVector[9]]=getValueOfTag();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getLiquibase())
            {
                ret[pMasqueradingVector[10]]=getValueOfLiquibase();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getContexts())
            {
                ret[pMasqueradingVector[11]]=getValueOfContexts();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getLabels())
            {
                ret[pMasqueradingVector[12]]=getValueOfLabels();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getDeploymentId())
            {
                ret[pMasqueradingVector[13]]=getValueOfDeploymentId();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAuthor())
    {
        ret["author"]=getValueOfAuthor();
    }
    else
    {
        ret["author"]=Json::Value();
    }
    if(getFilename())
    {
        ret["filename"]=getValueOfFilename();
    }
    else
    {
        ret["filename"]=Json::Value();
    }
    if(getDateexecuted())
    {
        ret["dateexecuted"]=getDateexecuted()->toDbStringLocal();
    }
    else
    {
        ret["dateexecuted"]=Json::Value();
    }
    if(getOrderexecuted())
    {
        ret["orderexecuted"]=getValueOfOrderexecuted();
    }
    else
    {
        ret["orderexecuted"]=Json::Value();
    }
    if(getExectype())
    {
        ret["exectype"]=getValueOfExectype();
    }
    else
    {
        ret["exectype"]=Json::Value();
    }
    if(getMd5sum())
    {
        ret["md5sum"]=getValueOfMd5sum();
    }
    else
    {
        ret["md5sum"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getComments())
    {
        ret["comments"]=getValueOfComments();
    }
    else
    {
        ret["comments"]=Json::Value();
    }
    if(getTag())
    {
        ret["tag"]=getValueOfTag();
    }
    else
    {
        ret["tag"]=Json::Value();
    }
    if(getLiquibase())
    {
        ret["liquibase"]=getValueOfLiquibase();
    }
    else
    {
        ret["liquibase"]=Json::Value();
    }
    if(getContexts())
    {
        ret["contexts"]=getValueOfContexts();
    }
    else
    {
        ret["contexts"]=Json::Value();
    }
    if(getLabels())
    {
        ret["labels"]=getValueOfLabels();
    }
    else
    {
        ret["labels"]=Json::Value();
    }
    if(getDeploymentId())
    {
        ret["deployment_id"]=getValueOfDeploymentId();
    }
    else
    {
        ret["deployment_id"]=Json::Value();
    }
    return ret;
}

bool Databasechangelog::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("author"))
    {
        if(!validJsonOfField(1, "author", pJson["author"], err, true))
            return false;
    }
    else
    {
        err="The author column cannot be null";
        return false;
    }
    if(pJson.isMember("filename"))
    {
        if(!validJsonOfField(2, "filename", pJson["filename"], err, true))
            return false;
    }
    else
    {
        err="The filename column cannot be null";
        return false;
    }
    if(pJson.isMember("dateexecuted"))
    {
        if(!validJsonOfField(3, "dateexecuted", pJson["dateexecuted"], err, true))
            return false;
    }
    else
    {
        err="The dateexecuted column cannot be null";
        return false;
    }
    if(pJson.isMember("orderexecuted"))
    {
        if(!validJsonOfField(4, "orderexecuted", pJson["orderexecuted"], err, true))
            return false;
    }
    else
    {
        err="The orderexecuted column cannot be null";
        return false;
    }
    if(pJson.isMember("exectype"))
    {
        if(!validJsonOfField(5, "exectype", pJson["exectype"], err, true))
            return false;
    }
    else
    {
        err="The exectype column cannot be null";
        return false;
    }
    if(pJson.isMember("md5sum"))
    {
        if(!validJsonOfField(6, "md5sum", pJson["md5sum"], err, true))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(7, "description", pJson["description"], err, true))
            return false;
    }
    if(pJson.isMember("comments"))
    {
        if(!validJsonOfField(8, "comments", pJson["comments"], err, true))
            return false;
    }
    if(pJson.isMember("tag"))
    {
        if(!validJsonOfField(9, "tag", pJson["tag"], err, true))
            return false;
    }
    if(pJson.isMember("liquibase"))
    {
        if(!validJsonOfField(10, "liquibase", pJson["liquibase"], err, true))
            return false;
    }
    if(pJson.isMember("contexts"))
    {
        if(!validJsonOfField(11, "contexts", pJson["contexts"], err, true))
            return false;
    }
    if(pJson.isMember("labels"))
    {
        if(!validJsonOfField(12, "labels", pJson["labels"], err, true))
            return false;
    }
    if(pJson.isMember("deployment_id"))
    {
        if(!validJsonOfField(13, "deployment_id", pJson["deployment_id"], err, true))
            return false;
    }
    return true;
}
bool Databasechangelog::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Databasechangelog::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    if(pJson.isMember("author"))
    {
        if(!validJsonOfField(1, "author", pJson["author"], err, false))
            return false;
    }
    if(pJson.isMember("filename"))
    {
        if(!validJsonOfField(2, "filename", pJson["filename"], err, false))
            return false;
    }
    if(pJson.isMember("dateexecuted"))
    {
        if(!validJsonOfField(3, "dateexecuted", pJson["dateexecuted"], err, false))
            return false;
    }
    if(pJson.isMember("orderexecuted"))
    {
        if(!validJsonOfField(4, "orderexecuted", pJson["orderexecuted"], err, false))
            return false;
    }
    if(pJson.isMember("exectype"))
    {
        if(!validJsonOfField(5, "exectype", pJson["exectype"], err, false))
            return false;
    }
    if(pJson.isMember("md5sum"))
    {
        if(!validJsonOfField(6, "md5sum", pJson["md5sum"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(7, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("comments"))
    {
        if(!validJsonOfField(8, "comments", pJson["comments"], err, false))
            return false;
    }
    if(pJson.isMember("tag"))
    {
        if(!validJsonOfField(9, "tag", pJson["tag"], err, false))
            return false;
    }
    if(pJson.isMember("liquibase"))
    {
        if(!validJsonOfField(10, "liquibase", pJson["liquibase"], err, false))
            return false;
    }
    if(pJson.isMember("contexts"))
    {
        if(!validJsonOfField(11, "contexts", pJson["contexts"], err, false))
            return false;
    }
    if(pJson.isMember("labels"))
    {
        if(!validJsonOfField(12, "labels", pJson["labels"], err, false))
            return false;
    }
    if(pJson.isMember("deployment_id"))
    {
        if(!validJsonOfField(13, "deployment_id", pJson["deployment_id"], err, false))
            return false;
    }
    return true;
}
bool Databasechangelog::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Databasechangelog::validJsonOfField(size_t index,
                                         const std::string &fieldName,
                                         const Json::Value &pJson,
                                         std::string &err,
                                         bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 10)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 10)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 35)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 35)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 10)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 10)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
