/**
 *
 *  TblIssueLabel.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "TblIssueLabel.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::distcomp;

const std::string TblIssueLabel::Cols::_id = "\"id\"";
const std::string TblIssueLabel::Cols::_issue_id = "\"issue_id\"";
const std::string TblIssueLabel::Cols::_label_id = "\"label_id\"";
const std::string TblIssueLabel::primaryKeyName = "id";
const bool TblIssueLabel::hasPrimaryKey = true;
const std::string TblIssueLabel::tableName = "\"tbl_issue_label\"";

const std::vector<typename TblIssueLabel::MetaData> TblIssueLabel::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"issue_id","int64_t","bigint",8,0,0,1},
{"label_id","int64_t","bigint",8,0,0,1}
};
const std::string &TblIssueLabel::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TblIssueLabel::TblIssueLabel(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["issue_id"].isNull())
        {
            issueId_=std::make_shared<int64_t>(r["issue_id"].as<int64_t>());
        }
        if(!r["label_id"].isNull())
        {
            labelId_=std::make_shared<int64_t>(r["label_id"].as<int64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            issueId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            labelId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }

}

TblIssueLabel::TblIssueLabel(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            issueId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            labelId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

TblIssueLabel::TblIssueLabel(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("issue_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["issue_id"].isNull())
        {
            issueId_=std::make_shared<int64_t>((int64_t)pJson["issue_id"].asInt64());
        }
    }
    if(pJson.isMember("label_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["label_id"].isNull())
        {
            labelId_=std::make_shared<int64_t>((int64_t)pJson["label_id"].asInt64());
        }
    }
}

void TblIssueLabel::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            issueId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            labelId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void TblIssueLabel::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("issue_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["issue_id"].isNull())
        {
            issueId_=std::make_shared<int64_t>((int64_t)pJson["issue_id"].asInt64());
        }
    }
    if(pJson.isMember("label_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["label_id"].isNull())
        {
            labelId_=std::make_shared<int64_t>((int64_t)pJson["label_id"].asInt64());
        }
    }
}

const int64_t &TblIssueLabel::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TblIssueLabel::getId() const noexcept
{
    return id_;
}
void TblIssueLabel::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename TblIssueLabel::PrimaryKeyType & TblIssueLabel::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &TblIssueLabel::getValueOfIssueId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(issueId_)
        return *issueId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TblIssueLabel::getIssueId() const noexcept
{
    return issueId_;
}
void TblIssueLabel::setIssueId(const int64_t &pIssueId) noexcept
{
    issueId_ = std::make_shared<int64_t>(pIssueId);
    dirtyFlag_[1] = true;
}

const int64_t &TblIssueLabel::getValueOfLabelId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(labelId_)
        return *labelId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TblIssueLabel::getLabelId() const noexcept
{
    return labelId_;
}
void TblIssueLabel::setLabelId(const int64_t &pLabelId) noexcept
{
    labelId_ = std::make_shared<int64_t>(pLabelId);
    dirtyFlag_[2] = true;
}

void TblIssueLabel::updateId(const uint64_t id)
{
}

const std::vector<std::string> &TblIssueLabel::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "issue_id",
        "label_id"
    };
    return inCols;
}

void TblIssueLabel::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIssueId())
        {
            binder << getValueOfIssueId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLabelId())
        {
            binder << getValueOfLabelId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TblIssueLabel::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void TblIssueLabel::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIssueId())
        {
            binder << getValueOfIssueId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLabelId())
        {
            binder << getValueOfLabelId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TblIssueLabel::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIssueId())
    {
        ret["issue_id"]=(Json::Int64)getValueOfIssueId();
    }
    else
    {
        ret["issue_id"]=Json::Value();
    }
    if(getLabelId())
    {
        ret["label_id"]=(Json::Int64)getValueOfLabelId();
    }
    else
    {
        ret["label_id"]=Json::Value();
    }
    return ret;
}

std::string TblIssueLabel::toString() const
{
    return toJson().toStyledString();
}

Json::Value TblIssueLabel::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getIssueId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfIssueId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getLabelId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfLabelId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIssueId())
    {
        ret["issue_id"]=(Json::Int64)getValueOfIssueId();
    }
    else
    {
        ret["issue_id"]=Json::Value();
    }
    if(getLabelId())
    {
        ret["label_id"]=(Json::Int64)getValueOfLabelId();
    }
    else
    {
        ret["label_id"]=Json::Value();
    }
    return ret;
}

bool TblIssueLabel::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("issue_id"))
    {
        if(!validJsonOfField(1, "issue_id", pJson["issue_id"], err, true))
            return false;
    }
    else
    {
        err="The issue_id column cannot be null";
        return false;
    }
    if(pJson.isMember("label_id"))
    {
        if(!validJsonOfField(2, "label_id", pJson["label_id"], err, true))
            return false;
    }
    else
    {
        err="The label_id column cannot be null";
        return false;
    }
    return true;
}
bool TblIssueLabel::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TblIssueLabel::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("issue_id"))
    {
        if(!validJsonOfField(1, "issue_id", pJson["issue_id"], err, false))
            return false;
    }
    if(pJson.isMember("label_id"))
    {
        if(!validJsonOfField(2, "label_id", pJson["label_id"], err, false))
            return false;
    }
    return true;
}
bool TblIssueLabel::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TblIssueLabel::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
