spring.application.name=discussion
server.port=24130
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=distcomp
spring.cassandra.schema-action=none
spring.liquibase.change-log=classpath:db/changelog-cassandra/db.changelog-master.xml
spring.liquibase.driver-class-name=com.ing.data.cassandra.jdbc.CassandraDriver
spring.liquibase.url=jdbc:cassandra://127.0.0.1:9042/distcomp?localdatacenter=datacenter1&compliancemode=Liquibase

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.admin.fail-fast=true
spring.kafka.admin.properties.default.api.timeout.ms=10000
spring.kafka.admin.properties.request.timeout.ms=10000
spring.kafka.consumer.group-id=discussion-notice-in
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.linger-ms=5
spring.kafka.producer.batch-size=32768
spring.kafka.producer.buffer-memory=33554432

kafka.topic.in-topic=InTopic
kafka.topic.out-topic=OutTopic
