server.port=24110

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase ??? Postgres
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.application.name=publisher

# ????????? ??????? ??? ????? ? ??????? discussion
discussion.base-url=http://localhost:24130
discussion.mock=false