server.port=24130

spring.application.name=distcomp-discussion

spring.jackson.default-property-inclusion=non_null

publisher.base-url=http://localhost:24110

spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=distcomp
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=distcomp-discussion-reactions
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.acks=all

kafka.topic.in=InTopic
kafka.topic.out=OutTopic
