spring.application.name=discussion
server.port=24130
server.address=localhost

spring.cassandra.schema-action=create-if-not-exists

# Cassandra
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=distcomp
spring.cassandra.local-datacenter=datacenter1


discussion.db.init-cql=classpath:db/cassandra/001-init-discussion.cql
