server.port=24110

# ???????????? ? ????? ???? ?? Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp_v2
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JWT Secret
jwt.secret=9a4f2c8d3b7a1e5f8g2h6j4k9l0m7n3o1p5q8r2s6t9u0v1w4x7y2z
jwt.expiration=3600000