services:
  service-1:
    build: ./module-discussion
    container_name: module-discussion
    ports:
      - "24130:24130"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      cassandra-init:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/distcomp
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_CASSANDRA_CONTACT_POINTS: cassandra
      SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
      SPRING_CASSANDRA_KEYSPACE_NAME: distcomp
      PUBLISHER_URL: http://module-publisher:24110

  service-2:
    build: ./module-publisher
    container_name: module-publisher
    ports:
      - "24110:24110"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      cassandra-init:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/distcomp
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_CASSANDRA_CONTACT_POINTS: cassandra
      SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
      SPRING_CASSANDRA_KEYSPACE_NAME: distcomp
      DISCUSSION_URL: http://module-discussion:24130

  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: distcomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_KEYSPACE: distcomp
    healthcheck:
      test: [ "CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
  cassandra-init:
    image: cassandra:latest
    container_name: cassandra-init
    depends_on:
      cassandra:
        condition: service_healthy
    command: /bin/bash -c "echo \"CREATE KEYSPACE IF NOT EXISTS distcomp WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};\" | cqlsh cassandra"

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  postgres_data:
  redis_data: