server.port=24110

app.kafka.request-reply-timeout-ms=30000

security.jwt.secret=1234567890
security.jwt.ttl-seconds=3600

spring.datasource.url=jdbc:postgresql://localhost:5433/distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate

redis.server = localhost
redis.port = 6379

spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=CommentActionDto:by.bsuir.publisher.dto.CommentActionDto

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=publisher
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=CommentActionDto:by.bsuir.publisher.dto.CommentActionDto
#spring.kafka.producer.transaction-id-prefix=tx-
#spring.kafka.consumer.isolation-level=read-committed
#spring.kafka.consumer.auto-offset-reset=earliest



topic.inTopic=InTopic
topic.outTopic=OutTopic
topic.commentChangeTopic=commentChangeTopic