server:
  port: 24110

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml