# ???? ??????????
server.port=24130

# ????????? ??????????? ? Cassandra
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=distcomp

# ????????? ????? (???????? keyspace, ???? ??? ???)
# ????????: ??? ?????????? ??? ?????? false, ?? ??? ????? ??????
spring.cassandra.schema-action=create_if_not_exists

# ??????????? SQL-???????? ???????? (CQL)
logging.level.org.springframework.data.cassandra.core.cql=DEBUG

# ????????? Liquibase ??? Cassandra (???????? ???????)
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
# ????????? ??????? ? URL ?????????? ??? Cassandra, ???? ??????????? ??????????
# spring.datasource.url=jdbc:cassandra://localhost:9042/distcomp