services:
  postgres:
    image: postgres:16
    container_name: jpa_lab_postgres
    environment:
      POSTGRES_DB: distcomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - jpa_lab_postgres:/var/lib/postgresql/data

volumes:
  jpa_lab_postgres:
