version: '3.8'

services:
  distcomp-db:
    image: postgres
    container_name: distcomp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - distcomp_db_data:/var/lib/postgresql/data
    networks:
      - distcomp-network

  cassandra:
    image: cassandra:latest
    container_name: distcomp-cassandra
    restart: unless-stopped
    ports:
      - "${CASSANDRA_PORT}:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=distcomp_cluster
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - distcomp-network

#  user-service:
#    build: .
#    container_name: user-service-app
#    restart: unless-stopped
#    ports:
#      - "24110:24110"
#    environment:
#      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
#      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/${DB_NAME}
#      SPRING_DATASOURCE_USERNAME: ${DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#    depends_on:
#      - user-db
#    networks:
#      - user-network

  redis:
    image: redis:latest
    container_name: distcomp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - distcomp-network
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: distcomp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - distcomp-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: distcomp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - distcomp-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: distcomp-kafka-ui
    depends_on:
      - kafka
    ports:
      - "10010:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - distcomp-network

networks:
  distcomp-network:
    driver: bridge

volumes:
  distcomp_db_data:
  cassandra_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  redis_data:
