<<<<<<< HEAD
server.port=24110
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp?currentSchema=distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=distcomp
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=distcomp
=======
spring.application.name=Distcomp
server.port=24110
spring.jackson.serialization.write-dates-as-timestamps=false
>>>>>>> f26c601fbbe43710c18d4d0b9d78ec1d65a1357c
