spring.application.name=DistComp
server.port=24130
server.address=0.0.0.0

spring.datasource.url=jdbc:cassandra://${SPRING_CASSANDRA_CONTACT_POINTS:localhost}:9042/distcomp?localdatacenter=datacenter1
spring.datasource.driver-class-name=com.ing.data.cassandra.jdbc.CassandraDriver

spring.cassandra.contact-points=${SPRING_CASSANDRA_CONTACT_POINTS:localhost}
spring.cassandra.port=9042
spring.cassandra.local-datacenter=${SPRING_CASSANDRA_LOCAL_DATACENTER:datacenter1}
spring.cassandra.keyspace-name=${SPRING_CASSANDRA_KEYSPACE_NAME:distcomp}

spring.cassandra.schema-action=create_if_not_exists
spring.cassandra.request.timeout=20s
spring.cassandra.connection.connect-timeout=30s
spring.cassandra.connection.init-query-timeout=30s

spring.liquibase.enabled=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.listener.ack-mode=record