# Spring Boot (PostgreSQL, Liquibase)
server.port=24110
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# --- Redis configuration ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.cache.type=redis

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

# --- Kafka configuration ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=publisher-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka topics
app.kafka.in-topic=in-topic
app.kafka.out-topic=out-topic

# Logging
logging.level.org.example.newsapi.controller=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

# --- JWT Configuration ---
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=3600000

# --- Spring Security (disable basic auth after testing, optional) ---
spring.security.basic.enabled=false