spring.application.name=demo
server.port=24110
server.address=localhost
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp?currentSchema=distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=distcomp
spring.jpa.open-in-view=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
discussion.base-url=http://localhost:24130