server.port=24110
server.servlet.context-path=/api/v1.0

# ????????: ????? ?????? /distcomp ?????? /postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp?currentSchema=distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
# ??? ?????? ??????? Hibernate ?? ?????? ?????
spring.jpa.properties.hibernate.default_schema=distcomp

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=distcomp