// <auto-generated />
using ArticleHouse.DAO.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArticleHouse.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260307221331_RemovedComments")]
    partial class RemovedComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleHouse.DAO.Models.ArticleMark", b =>
                {
                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint")
                        .HasColumnName("article_id");

                    b.Property<long>("MarkId")
                        .HasColumnType("bigint")
                        .HasColumnName("mark_id");

                    b.HasKey("ArticleId", "MarkId")
                        .HasName("pk_article_mark");

                    b.HasIndex("MarkId")
                        .HasDatabaseName("ix_article_mark_mark_id");

                    b.ToTable("article_mark", (string)null);
                });

            modelBuilder.Entity("ArticleHouse.DAO.Models.ArticleModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tbl_article");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_tbl_article_creator_id");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("ix_tbl_article_title");

                    b.ToTable("tbl_article", (string)null);
                });

            modelBuilder.Entity("ArticleHouse.DAO.Models.CreatorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_tbl_creator");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_tbl_creator_login");

                    b.ToTable("tbl_creator", (string)null);
                });

            modelBuilder.Entity("ArticleHouse.DAO.Models.MarkModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tbl_mark");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tbl_mark_name");

                    b.ToTable("tbl_mark", (string)null);
                });

            modelBuilder.Entity("ArticleHouse.DAO.Models.ArticleMark", b =>
                {
                    b.HasOne("ArticleHouse.DAO.Models.ArticleModel", "Article")
                        .WithMany("ArticleMarks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_mark_tbl_article_article_id");

                    b.HasOne("ArticleHouse.DAO.Models.MarkModel", "Mark")
                        .WithMany("ArticleMarks")
                        .HasForeignKey("MarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_mark_tbl_mark_mark_id");

                    b.Navigation("Article");

                    b.Navigation("Mark");
                });

            modelBuilder.Entity("ArticleHouse.DAO.Models.ArticleModel", b =>
                {
                    b.HasOne("ArticleHouse.DAO.Models.CreatorModel", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_article_tbl_creator_creator_id");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ArticleHouse.DAO.Models.ArticleModel", b =>
                {
                    b.Navigation("ArticleMarks");
                });

            modelBuilder.Entity("ArticleHouse.DAO.Models.MarkModel", b =>
                {
                    b.Navigation("ArticleMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
