spring:
  application:
    name: discussion

  mvc:
    apiversion:
      use:
        path-segment: 1
      supported: 1.0, 2.0
      default: 1.0

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: distcomp
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: publisher-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.discussion.dto.kafka.KafkaNoticeRequest

kafka:
  topics:
    in: InTopic
    out: OutTopic

server:
  port: 24130