# Generated by Django 6.0.2 on 2026-02-23 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_story_writerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
