spring.application.name=discussion
server.port=24130

# ????????? ??? Liquibase (JDBC) - ?????????? ??? ???? ? ????, ?? ? ?????? Keyspace
spring.datasource.url=jdbc:cassandra://127.0.0.1:9042/distcomp?localdatacenter=datacenter1&compliancemode=Liquibase
spring.datasource.driver-class-name=com.ing.data.cassandra.jdbc.CassandraDriver
spring.datasource.username=
spring.datasource.password=

# ????????? ??? Spring Data Cassandra (Native Driver)
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=distcomp
spring.cassandra.schema-action=none

# ????????? ?????? Liquibase
spring.liquibase.driver-class-name=com.ing.data.cassandra.jdbc.CassandraDriver
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# ????????? ??? ?? URL, ??? ? ? datasource
spring.liquibase.url=jdbc:cassandra://127.0.0.1:9042/distcomp?localdatacenter=datacenter1&compliancemode=Liquibase

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.properties.spring.json.value.default.type=org.discussion.other.record.CommentUploadRecord
