version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: distcomp-postgres
    environment:
      POSTGRES_DB: distcomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:4.1
    container_name: my-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  postgres_data:
  cassandra_data: