server.port=24110
spring.mvc.servlet.path=/api/v1.0

# Настройки подключения к Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp?currentSchema=distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Настройка Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=distcomp