server:
  port: 24110

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: distcomp
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: distcomp