spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: dictcomp
    liquibase-schema: dictcomp

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 20000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  security:
    user:
      name: admin
      password: admin

server:
  port: 24110

jwt:
  secret: mySuperSecretKey1234567890123456789012345678901234567890
  expiration:
    ms: 86400000

logging:
  level:
    root: WARN
    com.example.demo: INFO
    org.springframework.web: WARN
