spring.application.name=MessageService

server.port=24130

discussion.cassandra.host=localhost
discussion.cassandra.port=9042
discussion.cassandra.keyspace=distcomp
discussion.cassandra.local-datacenter=datacenter1
discussion.cassandra.bucket-count=8

spring.kafka.bootstrap-servers=localhost:9092
app.kafka.in-topic=InTopic
app.kafka.out-topic=OutTopic
app.kafka.discussion-group=discussion-group

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:8888/eureka
