# Generated by Django 6.0.1 on 2026-02-27 16:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('login', models.EmailField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('firstname', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lastname', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
                ('content', models.TextField(max_length=2048, validators=[django.core.validators.MinLengthValidator(4)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.editor')),
                ('labels', models.ManyToManyField(related_name='issues', to='api.label')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(max_length=2048, validators=[django.core.validators.MinLengthValidator(2)])),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.issue')),
            ],
        ),
    ]
