# Generated by Django 6.0.1 on 2026-02-27 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='login',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
