# Generated by Django 6.0.1 on 2026-02-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_editor_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='editor',
            table='tbl_editor',
        ),
        migrations.AlterModelTable(
            name='issue',
            table='tbl_issue',
        ),
        migrations.AlterModelTable(
            name='label',
            table='tbl_label',
        ),
        migrations.AlterModelTable(
            name='message',
            table='tbl_message',
        ),
    ]
