# Generated by Django 6.0.1 on 2026-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_editor_table_alter_issue_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=10),
        ),
    ]
