# Generated by Django 6.0.1 on 2026-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_editor_groups_editor_is_active_editor_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='role',
            field=models.CharField(default='CUSTOMER', max_length=50),
        ),
    ]
