# Generated by Django 6.0.1 on 2026-05-08 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_editor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='editor',
            name='firstname',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='editor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='lastname',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='editor',
            name='login',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='editor',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterModelTable(
            name='editor',
            table='tbl_editor',
        ),
    ]
