# Generated by Django 6.0.1 on 2026-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_editor_groups_remove_editor_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10),
        ),
    ]
