server.port=24110
spring.application.name=publisher

spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.kafka.consumer.group-id=publisher-group
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.common.dto

spring.cassandra.local-datacenter=datacenter1

spring.data.redis.host=localhost
spring.data.redis.port=6379
app.cache.ttl=600000

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=3600000
