server:
  port: 24130

spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: distcomp
      schema-action: create-if-not-exists
      local-datacenter: datacenter1

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: discussion-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
