"""Initial

Revision ID: 4e9ee2df7c29
Revises: 
Create Date: 2026-03-08 21:49:00.999738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9ee2df7c29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_editor',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('tbl_marker',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_tweet',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('editor_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['tbl_editor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_post',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tbl_tweet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_tweet_marker',
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('marker_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['marker_id'], ['tbl_marker.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tweet_id'], ['tbl_tweet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tweet_id', 'marker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_tweet_marker')
    op.drop_table('tbl_post')
    op.drop_table('tbl_tweet')
    op.drop_table('tbl_marker')
    op.drop_table('tbl_editor')
    # ### end Alembic commands ###
