spring.cassandra.contact-points=cassandra
spring.cassandra.port=9042
spring.cassandra.keyspace-name=task361

spring.kafka.bootstrap-servers=kafka:29092
app.jwt.secret=task361-jwt-secret-task361-jwt-secret-1234567890
