server.port=24130

# ========== SPRING DATA CASSANDRA (?????????? ?????????) ==========
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=distcomp
spring.cassandra.local-datacenter=datacenter1

# ?????????????? ???????? ?????? (??? ??????????)
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS