# Generated by Django 6.0.1 on 2026-05-06 18:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('firstname', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lastname', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'db_table': 'tbl_author',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'db_table': 'tbl_mark',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
                ('content', models.TextField(max_length=2048, validators=[django.core.validators.MinLengthValidator(4)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='api.author')),
                ('marks', models.ManyToManyField(blank=True, db_table='tbl_tweet_marks', related_name='tweets', to='api.mark')),
            ],
            options={
                'db_table': 'tbl_tweet',
            },
        ),
    ]
