changeLogFile=/liquibase/changelog/db.changelog-master.xml
url=jdbc:postgresql://postgres:5432/distcomp
username=postgres
password=postgres
driver=org.postgresql.Driver
classpath=/liquibase/lib/postgresql-42.7.1.jar
logLevel=INFO