server.port=24110

# ????????? ???? ?????? (??? currentSchema)
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase (??? ?????????? ????)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.application.name=distcomp