server.port=24130

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=distcomp
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=none

spring.jackson.serialization.write-dates-as-timestamps=false
