server.port=24130
server.servlet.context-path=/api/v1.0

spring.cassandra.keyspace-name=distcomp
spring.cassandra.contact-points=localhost:9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=recreate_drop_unused

# Увеличиваем время на подключение и запросы (до 10 секунд)
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
spring.cassandra.request.timeout=10s

# Настройки Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=discussion-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3